DROP TABLE PRODUCTOSALIMENTARIOS;
DROP TABLE PRODUCTOSELECTRONICOS 
CREATE OR REPLACE TYPE PRODUCTO AS OBJECT(
CODIGO VARCHAR2(10),
NOMBRE VARCHAR2(100),
CATEGORIA VARCHAR2(50),
PRECIO NUMBER(10,2),
MEMBER FUNCTION OBTENERETIQUETA RETURN VARCHAR2
)NOT FINAL;
/

CREATE OR REPLACE TYPE BODY PRODUCTO AS
    MEMBER FUNCTION OBTENERETIQUETA RETURN VARCHAR2 IS
    BEGIN
        RETURN DBMS_OUTPUT.PUT_LINE(CODIGO || '' || NOMBRE || '' || CATEGORIA);
    END;
END;
/

CREATE TYPE PRODUCTOELECTRONICO UNDER PRODUCTO (
GARANTIA_MESES NUMBER,
MEMBER PROCEDURE APLICARDESCUENTO(PORCENTAJE NUMBER)
);
/

CREATE OR REPLACE TYPE BODY PRODUCTOELECTRONICO AS
    MEMBER PROCEDURE APLICARDESCUENTO(PORCENTAJE NUMBER) IS
    BEGIN
    SELF.PRECIO := SELF.PRECIO - (SELF.PRECIO * PORCENTAJE/100);
    END;
END;
/

CREATE TYPE PRODUCTOALIMENTARIO UNDER PRODUCTO (
CALORIAS_POR_100G NUMBER,
MEMBER PROCEDURE APLICARDESCUENTO(PORCENTAJE NUMBER)
);
/

CREATE TABLE PRODUCTOSELECTRONICOS OF PRODUCTOELECTRONICO;
CREATE TABLE PRODUCTOSALIMENTARIOS OF PRODUCTOALIMENTARIO;

DECLARE
PE1 PRODUCTOELECTRONICO;
BEGIN
PE1:=PRODUCTOELECTRONICO ('Elec001','TelevisorOLED','Electronica',800,24);

PE2:=PRODUCTOELECTRONICO ('Elec002','Smartphone Pro','Electronica',600,12);

-- Aplicar descuento del 10%
PE1.APLICARDESCUENTO(10);-- 10
PE2.APLICARDESCUENTO(15);-- 15
-- Insertar objetos en tablas
INSERT INTO TABLE (PRODUCTOSELECTRONICOS) VALUES(PE1);
INSERT INTO TABLE (PRODUCTOSELECTRONICOS) VALUES(PE2);
-- Mostrar precios tras descuento con dbms_output
DBMS_OUTPUT.PUT_LINE(PE1);
DBMS_OUTPUT.PUT_LINE(PE2);
END;
end;